import type { WeaponCard } from "@cards/shared";

export const weapons: WeaponCard[] = [
  // ── Physical: 1 basic per type + 1 special ──
  {
    type: "weapon",
    id: "iron-sword",
    name: "Iron Sword",
    attackType: "sword",
    statBoost: { str: 3 },
    effects: [],
    cost: 1,
    flavor: "Reliable and unadorned.",
  },
  {
    type: "weapon",
    id: "brave-sword",
    name: "Brave Sword",
    attackType: "sword",
    statBoost: { str: 2 },
    effects: [{ kind: "double_attack" }],
    cost: 4,
    flavor: "Swing once? Why not twice.",
  },
  {
    type: "weapon",
    id: "iron-axe",
    name: "Iron Axe",
    attackType: "axe",
    statBoost: { str: 4 },
    effects: [],
    cost: 1,
    flavor: "Simple, brutal, effective.",
  },
  {
    type: "weapon",
    id: "hammer",
    name: "Hammer",
    attackType: "axe",
    statBoost: { str: 3 },
    effects: [{ kind: "damage_multiplier_vs_tag", tag: "armored", multiplier: 2 }],
    cost: 3,
    flavor: "Dents armor like tin foil.",
  },
  {
    type: "weapon",
    id: "iron-lance",
    name: "Iron Lance",
    attackType: "lance",
    statBoost: { str: 3 },
    effects: [],
    cost: 1,
    flavor: "Reach is everything.",
  },
  {
    type: "weapon",
    id: "javelin",
    name: "Javelin",
    attackType: "lance",
    statBoost: { str: 2 },
    effects: [{ kind: "ranged" }],
    cost: 2,
    flavor: "Throw it. Hit them.",
  },
  {
    type: "weapon",
    id: "iron-bow",
    name: "Iron Bow",
    attackType: "bow",
    statBoost: { str: 3 },
    effects: [{ kind: "ranged" }],
    cost: 1,
    flavor: "A huntsman's companion.",
  },

  // ── Tomes: 1 basic per type + 1 special ──
  {
    type: "weapon",
    id: "fire-tome",
    name: "Fire",
    attackType: "fire",
    statBoost: { mag: 3 },
    effects: [],
    cost: 1,
    flavor: "The most fundamental anima spell.",
  },
  {
    type: "weapon",
    id: "wind-tome",
    name: "Wind",
    attackType: "wind",
    statBoost: { mag: 3 },
    effects: [],
    cost: 1,
    flavor: "A cutting gale at your command.",
  },
  {
    type: "weapon",
    id: "excalibur-tome",
    name: "Excalibur",
    attackType: "wind",
    statBoost: { mag: 4 },
    effects: [{ kind: "damage_multiplier_vs_tag", tag: "flying", multiplier: 2 }],
    cost: 3,
    flavor: "The legendary wind that grounds all wings.",
  },
  {
    type: "weapon",
    id: "thunder-tome",
    name: "Thunder",
    attackType: "thunder",
    statBoost: { mag: 3 },
    effects: [],
    cost: 1,
    flavor: "A bolt from an outstretched hand.",
  },
];
