import type { TournamentOpponent } from "./types.js";

/**
 * The 8-opponent ladder. Ordered 1..8; difficulty and AI preset climb
 * together per docs/TOURNAMENT_MODE.md §3.
 *
 * Deck composition rules (enforced by ./validate.ts):
 *   - Length === DECK_SIZE (15).
 *   - Exactly 1 Lord.
 *   - Max MAX_CARD_COPIES (2) of any card (Lords always 1).
 *   - Every card ID must resolve via getCardById.
 *   - rewardCardId must NOT appear in STARTER_POOL.
 *   - All 8 rewardCardIds are mutually distinct.
 *
 * Decks are intentionally not restricted to the starter pool — themed
 * opponents showcase cards the player will eventually unlock.
 */
export const OPPONENTS: readonly TournamentOpponent[] = [
  {
    id: "recruit-gareth",
    order: 1,
    displayName: "Recruit Gareth",
    archetype: "infantry",
    blurb: "A green sword-hand with more spirit than skill.",
    ai: "easy",
    deck: [
      "lord-marth",
      "mercenary-raven",
      "mercenary-raven",
      "swordmaster-karel",
      "swordmaster-karel",
      "thief-matthew",
      "thief-matthew",
      "iron-sword",
      "iron-sword",
      "iron-lance",
      "iron-axe",
      "vulnerary",
      "vulnerary",
      "tactic-rally",
      "tactic-convoy",
    ],
    // Cleric — cheap, flexible support unit. Thematic follow-up to vanilla infantry.
    rewardCardId: "cleric-serra",
  },
  {
    id: "archer-mila",
    order: 2,
    displayName: "Archer Mila",
    archetype: "bow",
    blurb: "Picks targets from the back line and never misses twice.",
    ai: "easy",
    deck: [
      "lord-marth",
      "archer-wil",
      "archer-wil",
      "mercenary-raven",
      "mercenary-raven",
      "thief-matthew",
      "thief-matthew",
      "iron-bow",
      "iron-bow",
      "iron-sword",
      "iron-sword",
      "javelin",
      "javelin",
      "vulnerary",
      "tactic-rally",
    ],
    // Bolting — ranged strike tactic, the archer's long-shot payoff.
    rewardCardId: "tactic-bolting",
  },
  {
    id: "cavalier-dorn",
    order: 3,
    displayName: "Cavalier Dorn",
    archetype: "mounted",
    blurb: "Rushes the flanks before the line can re-form.",
    ai: "medium",
    deck: [
      "lord-ephraim",
      "troubadour-priscilla",
      "troubadour-priscilla",
      "knight-oswin",
      "knight-oswin",
      "mercenary-raven",
      "mercenary-raven",
      "iron-lance",
      "iron-lance",
      "javelin",
      "javelin",
      "iron-sword",
      "vulnerary",
      "energy-ring",
      "tactic-rally",
    ],
    // Troubadour — the catalog's only mounted unit. Mobile healer.
    rewardCardId: "troubadour-priscilla",
  },
  {
    id: "skyrider-ilyana",
    order: 4,
    displayName: "Skyrider Ilyana",
    archetype: "flying",
    blurb: "Strikes from above. Your archers had better be ready.",
    ai: "medium",
    deck: [
      "lord-ephraim",
      "pegasus-florina",
      "pegasus-florina",
      "wyvern-heath",
      "wyvern-heath",
      "support-sky-sisters",
      "support-sky-sisters",
      "iron-lance",
      "iron-lance",
      "javelin",
      "javelin",
      "vulnerary",
      "speedwings",
      "tactic-rally",
      "tactic-rescue",
    ],
    // Pegasus — signature flying unit the player can now field.
    rewardCardId: "pegasus-florina",
  },
  {
    id: "mage-veyra",
    order: 5,
    displayName: "Mage Veyra",
    archetype: "magic",
    blurb: "Three schools of anima. One very bad afternoon.",
    ai: "medium",
    deck: [
      "lord-marth",
      "mage-lilina",
      "mage-lilina",
      "mage-nino",
      "mage-nino",
      "mage-lugh",
      "mage-lugh",
      "fire-tome",
      "fire-tome",
      "wind-tome",
      "wind-tome",
      "thunder-tome",
      "tactic-bolting",
      "tactic-convoy",
      "vulnerary",
    ],
    // Meteor — the signature damage tactic of an arcane opponent.
    rewardCardId: "tactic-meteor",
  },
  {
    id: "armorlord-gorn",
    order: 6,
    displayName: "Armorlord Gorn",
    archetype: "armor",
    blurb: "A wall of plate and patience. You will break first.",
    ai: "hard",
    deck: [
      "lord-ephraim",
      "knight-oswin",
      "knight-oswin",
      "general-wallace",
      "general-wallace",
      "mercenary-raven",
      "silver-lance",
      "silver-lance",
      "iron-lance",
      "hammer",
      "goddess-icon",
      "goddess-icon",
      "tactic-aegis",
      "tactic-aegis",
      "elixir",
    ],
    // Silver Lance — high-impact weapon Silver tier, fits armored theme.
    rewardCardId: "silver-lance",
  },
  {
    id: "shadow-kael",
    order: 7,
    displayName: "Shadow Kael",
    archetype: "disruption",
    blurb: "Hits where you aren't looking. Then hits again.",
    ai: "hard",
    deck: [
      "lord-marth",
      "thief-matthew",
      "thief-matthew",
      "swordmaster-karel",
      "swordmaster-karel",
      "mercenary-raven",
      "mercenary-raven",
      "killing-edge",
      "killing-edge",
      "iron-sword",
      "iron-sword",
      "speedwings",
      "tactic-swap-posts",
      "tactic-rescue",
      "tactic-convoy",
    ],
    // Speedwings — disruption/tempo item. The thief's edge.
    rewardCardId: "speedwings",
  },
  {
    id: "champion-valdis",
    order: 8,
    displayName: "Champion Valdis",
    archetype: "champion",
    blurb: "Every lesson from every round. Concentrated.",
    ai: "expert",
    deck: [
      "lord-marth",
      "swordmaster-karel",
      "swordmaster-karel",
      "knight-oswin",
      "knight-oswin",
      "archer-wil",
      "archer-wil",
      "mercenary-raven",
      "rapier",
      "rapier",
      "silver-sword",
      "silver-lance",
      "support-brothers",
      "tactic-aegis",
      "elixir",
    ],
    // Rapier — the Lord's signature blade, effective vs armored AND flying.
    // Capstone reward: rare, bragging-rights card.
    rewardCardId: "rapier",
  },
];
